CREATE TABLE IF NOT EXISTS Scouting (
	EntryID	INTEGER,
	Stage	TEXT,
	SetNo	INTEGER,
	MatchNo	INTEGER,
	Team	INTEGER,
	PRIMARY KEY(EntryID)
);
INSERT INTO Scouting DEFAULT VALUES;
SELECT last_insert_rowid();